### ISSUE TITLE
Best GitHub Practices for Openstax!

### ISSUE THREAD

**Issue by philschatz** [openstax/napkin-notes#34]
# Proposal

Each repo has a `CONTRIBUTING.md` which:
1. links to `openstax/napkin-notes/CONTRIBUTING.md` (for example)
2. has repo-specific conventions

This way,

- whenever someone creates a PullRequest a link to that file shows up
  - so they can remember "How do I rebase again?"
  - can read about how to structure the code/tests
- people can suggest changes (via a PR to the file) and have an async discussion

/cc @openstax/tutor-fe @jpslav @dak (feel free to edit this part to add others in here :smile: )

**Comment by dak** [comment]
Phil already discussed this with me in Slack. Just wanted to add I think this is an excellent idea.

The next trick will be writing a strawman for the global CONTRIBUTING.md file, wherever it may live, which I think Phil has volunteered to do by creating this issue.

**Comment by philschatz** [comment]
Closing this in favor of moving the discussion to a proposed solution in #35
